version: "3.9"
services:
  backend:
    container_name: gateway-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - shared_network

networks:
  shared_network:
    external: true
