version: "3.9"

services:
  gateway-backend:
    container_name: gateway-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4000:4000"
    networks:
      - shared-network

networks:
  shared-network:
    external: true


  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin-container-gateway-backend
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #   ports:
  #     - "5050:80"
      # networks:
      #   - mynetwork
  
  