version: "3.9"
services:
  backend:
    container_name: gateway-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container-gateway-backend
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"