version: "3.9"
services:
  auth-backend:
    container_name: auth-services-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "50052:50052"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
    networks:
      - shared-network

networks:
  shared-network:
    external: true