version: '3.9'

services:
  mqtt-backend:
    container_name: mqtt-service-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3006:3006"
    depends_on:
      - mqtt-broker

  mqtt-broker:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
volumes:
  config:
  data:
  log: