version: "3.9"
services:
  database:
    container_name: redis-database
    image: redis:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: redis
      POSTGRES_DB: redis
    volumes:
      - ./data:/var/lib/redis/data
    ports:
      - "6379:6379"
    healthcheck:
      test: psql -U redis -q -d redis -c "SELECT 'ready';"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  db-data: